#server:
#  port: 8888
server:
  port: 8888
spring:
  application:
    name: eureka-server${server.port}
eureka:
#  instance:
#    hostname: localhost
#    leaseRenewalIntervalInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false



#日志配置
logging:
  config: classpath:log4j2.xml